// <auto-generated />
using System;
using ImagenDiagnostico.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImagenDiagnostico.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505200949_AgregarInformesRadiologicos")]
    partial class AgregarInformesRadiologicos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImagenDiagnostico.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.EstudioRealizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ContrasteAplicado")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DosisRadiacion")
                        .HasColumnType("numeric");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoInforme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrdenImagenId")
                        .HasColumnType("integer");

                    b.Property<int>("TecnicoEjecutorId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEstudioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EquipoId");

                    b.HasIndex("OrdenImagenId");

                    b.HasIndex("TecnicoEjecutorId");

                    b.HasIndex("TipoEstudioId");

                    b.ToTable("EstudiosRealizados");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.InformeRadiologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstudioRealizadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hallazgos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Radiologo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EstudioRealizadoId");

                    b.ToTable("InformesRadiologicos");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.OrdenImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MedicoSolicitanteId")
                        .HasColumnType("integer");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Urgencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("OrdenesImagen");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.TecnicoEjecutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TecnicosEjecutores");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.TipoEstudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("RequiereContraste")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TiposEstudio");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.EstudioRealizado", b =>
                {
                    b.HasOne("ImagenDiagnostico.Models.Equipo", "Equipo")
                        .WithMany("EstudiosRealizados")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImagenDiagnostico.Models.OrdenImagen", "OrdenImagen")
                        .WithMany("EstudiosRealizados")
                        .HasForeignKey("OrdenImagenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImagenDiagnostico.Models.TecnicoEjecutor", "TecnicoEjecutor")
                        .WithMany("EstudiosRealizados")
                        .HasForeignKey("TecnicoEjecutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImagenDiagnostico.Models.TipoEstudio", "TipoEstudio")
                        .WithMany("EstudiosRealizados")
                        .HasForeignKey("TipoEstudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("OrdenImagen");

                    b.Navigation("TecnicoEjecutor");

                    b.Navigation("TipoEstudio");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.InformeRadiologico", b =>
                {
                    b.HasOne("ImagenDiagnostico.Models.EstudioRealizado", "EstudioRealizado")
                        .WithMany("InformesRadiologicos")
                        .HasForeignKey("EstudioRealizadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstudioRealizado");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.Equipo", b =>
                {
                    b.Navigation("EstudiosRealizados");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.EstudioRealizado", b =>
                {
                    b.Navigation("InformesRadiologicos");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.OrdenImagen", b =>
                {
                    b.Navigation("EstudiosRealizados");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.TecnicoEjecutor", b =>
                {
                    b.Navigation("EstudiosRealizados");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.TipoEstudio", b =>
                {
                    b.Navigation("EstudiosRealizados");
                });
#pragma warning restore 612, 618
        }
    }
}
