// <auto-generated />
using System;
using ImagenDiagnostico.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImagenDiagnostico.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426144845_InicialPostgres")]
    partial class InicialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImagenDiagnostico.Models.EstudioRealizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrdenImagenId")
                        .HasColumnType("integer");

                    b.Property<int>("TecnicoEjecutorId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEstudioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("OrdenImagenId");

                    b.HasIndex("TipoEstudioId");

                    b.ToTable("EstudiosRealizados");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.OrdenImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MedicoSolicitanteId")
                        .HasColumnType("integer");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Urgencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("OrdenesImagen");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.TipoEstudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TiposEstudio");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.EstudioRealizado", b =>
                {
                    b.HasOne("ImagenDiagnostico.Models.OrdenImagen", "OrdenImagen")
                        .WithMany("EstudiosRealizados")
                        .HasForeignKey("OrdenImagenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImagenDiagnostico.Models.TipoEstudio", "TipoEstudio")
                        .WithMany("EstudiosRealizados")
                        .HasForeignKey("TipoEstudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenImagen");

                    b.Navigation("TipoEstudio");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.OrdenImagen", b =>
                {
                    b.Navigation("EstudiosRealizados");
                });

            modelBuilder.Entity("ImagenDiagnostico.Models.TipoEstudio", b =>
                {
                    b.Navigation("EstudiosRealizados");
                });
#pragma warning restore 612, 618
        }
    }
}
